// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

/// Why the Flutter engine was started.
///
/// The enforcement service and the launcher icon open the same Activity, and the app
/// must not show the Front Desk when the user was reaching for Instagram.
enum LaunchReason {
  /// The user tapped our icon.
  icon,
  /// `ForegroundWatcher` saw Instagram come to the front. Show the Gate, nothing else.
  gate,
}

/// Grants Android makes us ask for by hand, each of which the user can revoke.
class Permissions {
  Permissions({
    required this.accessibility,
    required this.notificationAccess,
  });

  bool accessibility;

  bool notificationAccess;

  Object encode() {
    return <Object?>[
      accessibility,
      notificationAccess,
    ];
  }

  static Permissions decode(Object result) {
    result as List<Object?>;
    return Permissions(
      accessibility: result[0]! as bool,
      notificationAccess: result[1]! as bool,
    );
  }
}

/// A launchable app on this device, for the Blocklist screen.
///
/// Note what iOS could never provide here: a name. `FamilyActivityPicker` returns opaque
/// tokens by design (C-3), so the iOS build can only ever say "3 apps blocked". Android
/// gives us the label and the icon, which is why the Blocklist and the Gate can both name
/// the app they are talking about.
class InstalledApp {
  InstalledApp({
    required this.packageName,
    required this.label,
    this.icon,
  });

  String packageName;

  String label;

  /// PNG bytes, pre-scaled by the platform. Null when the icon could not be rendered —
  /// the row still works, it just shows initials.
  Uint8List? icon;

  Object encode() {
    return <Object?>[
      packageName,
      label,
      icon,
    ];
  }

  static InstalledApp decode(Object result) {
    result as List<Object?>;
    return InstalledApp(
      packageName: result[0]! as String,
      label: result[1]! as String,
      icon: result[2] as Uint8List?,
    );
  }
}

/// The little that native owns.
///
/// Deliberately small. Every rule lives in `packages/domain` and every decision is made
/// in Dart; the services only need to know whether to act and whether a permit is
/// currently running. If you find yourself wanting to add a rule here, put it in the
/// domain package and have Dart write the answer down instead.
class NativeState {
  NativeState({
    required this.blockingEnabled,
    required this.grantEndsAtEpochMs,
    required this.launchReason,
    required this.permissions,
    required this.lastWatcherHeartbeatEpochMs,
  });

  bool blockingEnabled;

  /// Epoch millis. 0 means no permit is running.
  int grantEndsAtEpochMs;

  LaunchReason launchReason;

  Permissions permissions;

  /// Epoch millis of the last time `ForegroundWatcher` was alive. 0 means never.
  ///
  /// This is the watchdog from D-010: OxygenOS kills background services and reverts
  /// battery exemptions on its own, and a blocker that dies quietly is worse than none.
  int lastWatcherHeartbeatEpochMs;

  Object encode() {
    return <Object?>[
      blockingEnabled,
      grantEndsAtEpochMs,
      launchReason,
      permissions,
      lastWatcherHeartbeatEpochMs,
    ];
  }

  static NativeState decode(Object result) {
    result as List<Object?>;
    return NativeState(
      blockingEnabled: result[0]! as bool,
      grantEndsAtEpochMs: result[1]! as int,
      launchReason: result[2]! as LaunchReason,
      permissions: result[3]! as Permissions,
      lastWatcherHeartbeatEpochMs: result[4]! as int,
    );
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is LaunchReason) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is Permissions) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is InstalledApp) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is NativeState) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : LaunchReason.values[value];
      case 130: 
        return Permissions.decode(readValue(buffer)!);
      case 131: 
        return InstalledApp.decode(readValue(buffer)!);
      case 132: 
        return NativeState.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class OfficeHostApi {
  /// Constructor for [OfficeHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  OfficeHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<NativeState> state() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.insta_killer.OfficeHostApi.state$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as NativeState?)!;
    }
  }

  /// Every launchable app, minus our own. Sorted by label.
  ///
  /// Slow enough to be worth calling once when the Blocklist opens rather than on every
  /// build — a few hundred packages, each with an icon to rasterise.
  Future<List<InstalledApp>> installedApps() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.insta_killer.OfficeHostApi.installedApps$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as List<Object?>?)!.cast<InstalledApp>();
    }
  }

  /// Re-scopes the accessibility service to exactly these packages.
  ///
  /// The manifest declares a static list, but the whole point is that the user chooses,
  /// so the service narrows itself at runtime. Passing an empty list means the watcher
  /// observes nothing at all, which is the correct reading of "no apps blocked".
  Future<void> setWatchedPackages(List<String> packageNames) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.insta_killer.OfficeHostApi.setWatchedPackages$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[packageNames]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> setBlockingEnabled(bool enabled) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.insta_killer.OfficeHostApi.setBlockingEnabled$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[enabled]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Suspends blocking until [endsAtEpochMs] and schedules the T-2min and T-0
  /// notifications (FR-19). The watcher reads the same timestamp, so a permit is
  /// honoured even if every alarm is dropped.
  Future<void> beginGrant(int endsAtEpochMs) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.insta_killer.OfficeHostApi.beginGrant$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[endsAtEpochMs]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// FR-21 — surrender. Cancels the alarms and resumes blocking immediately.
  Future<void> endGrant() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.insta_killer.OfficeHostApi.endGrant$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Dart owns the schema; native owns the file. Values are JSON written by the
  /// repository, opaque to Kotlin — which is what keeps the rules in one language.
  Future<String?> read(String key) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.insta_killer.OfficeHostApi.read$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[key]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return (pigeonVar_replyList[0] as String?);
    }
  }

  Future<void> write(String key, String value) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.insta_killer.OfficeHostApi.write$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[key, value]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> openAccessibilitySettings() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.insta_killer.OfficeHostApi.openAccessibilitySettings$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> openNotificationAccessSettings() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.insta_killer.OfficeHostApi.openNotificationAccessSettings$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Leaves the Gate to the launcher rather than back to Instagram underneath.
  Future<void> leaveToHome() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.insta_killer.OfficeHostApi.leaveToHome$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }
}

abstract class OfficeFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  /// Instagram was opened while the engine was already warm. Same meaning as
  /// [LaunchReason.gate], but for a process that did not have to start.
  void onGateRequested();

  /// An alarm fired and blocking resumed. The UI should stop counting down.
  void onGrantExpired();

  static void setUp(OfficeFlutterApi? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.insta_killer.OfficeFlutterApi.onGateRequested$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          try {
            api.onGateRequested();
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.insta_killer.OfficeFlutterApi.onGrantExpired$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          try {
            api.onGrantExpired();
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
