// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.aadarsh.insta_killer

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  return if (exception is FlutterError) {
    listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

private fun createConnectionError(channelName: String): FlutterError {
  return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/**
 * Why the Flutter engine was started.
 *
 * The enforcement service and the launcher icon open the same Activity, and the app
 * must not show the Front Desk when the user was reaching for Instagram.
 */
enum class LaunchReason(val raw: Int) {
  /** The user tapped our icon. */
  ICON(0),
  /** `ForegroundWatcher` saw Instagram come to the front. Show the Gate, nothing else. */
  GATE(1);

  companion object {
    fun ofRaw(raw: Int): LaunchReason? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * Grants Android makes us ask for by hand, each of which the user can revoke.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class Permissions (
  val accessibility: Boolean,
  val notificationAccess: Boolean,
  val instagramInstalled: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): Permissions {
      val accessibility = pigeonVar_list[0] as Boolean
      val notificationAccess = pigeonVar_list[1] as Boolean
      val instagramInstalled = pigeonVar_list[2] as Boolean
      return Permissions(accessibility, notificationAccess, instagramInstalled)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      accessibility,
      notificationAccess,
      instagramInstalled,
    )
  }
}

/**
 * The little that native owns.
 *
 * Deliberately small. Every rule lives in `packages/domain` and every decision is made
 * in Dart; the services only need to know whether to act and whether a permit is
 * currently running. If you find yourself wanting to add a rule here, put it in the
 * domain package and have Dart write the answer down instead.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class NativeState (
  val blockingEnabled: Boolean,
  /** Epoch millis. 0 means no permit is running. */
  val grantEndsAtEpochMs: Long,
  val launchReason: LaunchReason,
  val permissions: Permissions,
  /**
   * Epoch millis of the last time `ForegroundWatcher` was alive. 0 means never.
   *
   * This is the watchdog from D-010: OxygenOS kills background services and reverts
   * battery exemptions on its own, and a blocker that dies quietly is worse than none.
   */
  val lastWatcherHeartbeatEpochMs: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeState {
      val blockingEnabled = pigeonVar_list[0] as Boolean
      val grantEndsAtEpochMs = pigeonVar_list[1] as Long
      val launchReason = pigeonVar_list[2] as LaunchReason
      val permissions = pigeonVar_list[3] as Permissions
      val lastWatcherHeartbeatEpochMs = pigeonVar_list[4] as Long
      return NativeState(blockingEnabled, grantEndsAtEpochMs, launchReason, permissions, lastWatcherHeartbeatEpochMs)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      blockingEnabled,
      grantEndsAtEpochMs,
      launchReason,
      permissions,
      lastWatcherHeartbeatEpochMs,
    )
  }
}
private open class OfficeApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          LaunchReason.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          Permissions.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeState.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is LaunchReason -> {
        stream.write(129)
        writeValue(stream, value.raw)
      }
      is Permissions -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is NativeState -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface OfficeHostApi {
  fun state(): NativeState
  fun setBlockingEnabled(enabled: Boolean)
  /**
   * Suspends blocking until [endsAtEpochMs] and schedules the T-2min and T-0
   * notifications (FR-19). The watcher reads the same timestamp, so a permit is
   * honoured even if every alarm is dropped.
   */
  fun beginGrant(endsAtEpochMs: Long)
  /** FR-21 — surrender. Cancels the alarms and resumes blocking immediately. */
  fun endGrant()
  /**
   * Dart owns the schema; native owns the file. Values are JSON written by the
   * repository, opaque to Kotlin — which is what keeps the rules in one language.
   */
  fun read(key: String): String?
  fun write(key: String, value: String)
  fun openAccessibilitySettings()
  fun openNotificationAccessSettings()
  /** Leaves the Gate to the launcher rather than back to Instagram underneath. */
  fun leaveToHome()

  companion object {
    /** The codec used by OfficeHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      OfficeApiPigeonCodec()
    }
    /** Sets up an instance of `OfficeHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: OfficeHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.insta_killer.OfficeHostApi.state$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.state())
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.insta_killer.OfficeHostApi.setBlockingEnabled$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val enabledArg = args[0] as Boolean
            val wrapped: List<Any?> = try {
              api.setBlockingEnabled(enabledArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.insta_killer.OfficeHostApi.beginGrant$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val endsAtEpochMsArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.beginGrant(endsAtEpochMsArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.insta_killer.OfficeHostApi.endGrant$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.endGrant()
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.insta_killer.OfficeHostApi.read$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val keyArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.read(keyArg))
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.insta_killer.OfficeHostApi.write$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val keyArg = args[0] as String
            val valueArg = args[1] as String
            val wrapped: List<Any?> = try {
              api.write(keyArg, valueArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.insta_killer.OfficeHostApi.openAccessibilitySettings$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.openAccessibilitySettings()
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.insta_killer.OfficeHostApi.openNotificationAccessSettings$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.openNotificationAccessSettings()
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.insta_killer.OfficeHostApi.leaveToHome$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.leaveToHome()
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class OfficeFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by OfficeFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      OfficeApiPigeonCodec()
    }
  }
  /**
   * Instagram was opened while the engine was already warm. Same meaning as
   * [LaunchReason.gate], but for a process that did not have to start.
   */
  fun onGateRequested(callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.insta_killer.OfficeFlutterApi.onGateRequested$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(null) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  /** An alarm fired and blocking resumed. The UI should stop counting down. */
  fun onGrantExpired(callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.insta_killer.OfficeFlutterApi.onGrantExpired$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(null) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
}
